eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
 
management:
  endpoints:
    web:
      exposure:
        include:
        - '*'
        
spring:    
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true        
        
microservice:
  payment-service:
    endpoints:
      endpoint:
        uri: http://PAYMENT-SERVICE/payment/doPayment
       
  boot:
    admin:
      client:
        url:
        - http://localhost:8888        
